common_plugins:
  hermit: &hermit
    elastic/hermit#v1.0.2
  gcp: &gcp_auth
    gcp-workload-identity-federation#v1.4.0:
      audience: $GCP_CLOUD_AUDIENCE
      service-account: $GCP_CLOUD_SERVICE_ACCOUNT
  gcr: &gcr_auth
    planetscale/docker-login-gcr#v0.0.1:
      registries: [ "us-docker.pkg.dev", "us-west1-docker.pkg.dev" ]

steps:
  - group: "CI"
    key: "ci"
    if: build.tag == null
    steps:
      - id: "build"
        label: "Build"
        commands: "make installer"
        plugins:
          - *hermit
          - *gcp_auth
          - *gcr_auth
  - group: "Release"
    key: "ci"
    if: build.tag != null
    steps:
      - id: "build"
        label: "Build"
        commands: "make installer"
        plugins:
          - *hermit
          - *gcp_auth
          - *gcr_auth
      - id: "push"
        label: "Push"
        commands: "make installer PUSH=true"
        plugins:
          - *hermit
          - *gcp_auth
          - *gcr_auth
