#! /bin/bash
set -euo pipefail

export GCP_CLOUD_AUDIENCE
GCP_CLOUD_AUDIENCE="$(buildkite-agent secret get GCP_CLOUD_AUDIENCE)"
export GCP_CLOUD_SERVICE_ACCOUNT
GCP_CLOUD_SERVICE_ACCOUNT="$(buildkite-agent secret get GCP_CLOUD_SERVICE_ACCOUNT)"

# needed to pull groq's hermit-packages
export HERMIT_GITHUB_TOKEN
HERMIT_GITHUB_TOKEN="$(groqkite gh token)"

#
# Talos Build Config
#
export PLATFORM="linux/amd64"
export REGISTRY="us-west1-docker.pkg.dev/prj-c-cloud-dcinfra-bc27"
export USERNAME="talos"

# Mirrors the TAG variable definition in Makefile
export TAG=$(git describe --tag --always --dirty --match v[0-9]\*)

# Latest build from https://github.com/groq/siderolabs-pkgs
export PKGS="f66490f"
export PKGS_PREFIX="$REGISTRY/$USERNAME"

# Particular extension versions to include in the installer image (one per line)
# IMPORTANT: please specify @sha256 for each extension
EXTENSIONS=(
    ${REGISTRY}/${USERNAME}/iscsi-tools:v0.1.6@sha256:0626af03c510c684d7d9c5238e8bff84623f74df5278f254c901624f63b33307
)

EXTENSION_ARGS=""
for EXTENSION in "${EXTENSIONS[@]}"; do
  EXTENSION_ARGS+="--system-extension-image $EXTENSION "
done
export EXTENSION_ARGS
